// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj5Lu_Bz37-F56HxCc2DBeQQIfaVxq4sY',
    appId: '1:574178708884:web:30c300cf6ca4ab3ed19381',
    messagingSenderId: '574178708884',
    projectId: 'truecinema-43c97',
    authDomain: 'truecinema-43c97.firebaseapp.com',
    storageBucket: 'truecinema-43c97.firebasestorage.app',
    measurementId: 'G-HPRX47CRWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDfdBpFr7aYFwcwbarzuqIW_iDxbuolBw',
    appId: '1:574178708884:android:727268913ba5bc18d19381',
    messagingSenderId: '574178708884',
    projectId: 'truecinema-43c97',
    storageBucket: 'truecinema-43c97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR73WhF4YyHYXXHJHvhHFXhdfwB6QNX7c',
    appId: '1:574178708884:ios:43ae6abb0f6b3930d19381',
    messagingSenderId: '574178708884',
    projectId: 'truecinema-43c97',
    storageBucket: 'truecinema-43c97.firebasestorage.app',
    iosBundleId: 'com.example.truecinema',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR73WhF4YyHYXXHJHvhHFXhdfwB6QNX7c',
    appId: '1:574178708884:ios:43ae6abb0f6b3930d19381',
    messagingSenderId: '574178708884',
    projectId: 'truecinema-43c97',
    storageBucket: 'truecinema-43c97.firebasestorage.app',
    iosBundleId: 'com.example.truecinema',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj5Lu_Bz37-F56HxCc2DBeQQIfaVxq4sY',
    appId: '1:574178708884:web:00ef2d691aff2030d19381',
    messagingSenderId: '574178708884',
    projectId: 'truecinema-43c97',
    authDomain: 'truecinema-43c97.firebaseapp.com',
    storageBucket: 'truecinema-43c97.firebasestorage.app',
    measurementId: 'G-XQ0VVM648Z',
  );
}
